role:   squadron
id:     links
binary: owl

reactor:
  provider: tilt
  network:  octalnet-links
  context:  ./

  blueprints:
    - env:  dev
      path: ./infra/dev/Tiltfile

    - env:  staging
      path: ./infra/staging/Tiltfile

    - env:  prod
      path: ./infra/prod/Tiltfile
